#ci file to publish mkdocs site
name: deploy

on:
  push:
    branches:
      - main

jobs:
  build: 
    name: Github Pages deployment for Mkdocs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Mkdocs site 
        run: |
          git pull
          mkdocs gh-deploy    